version: '3.9'
services:
  pg-db:
    container_name: pg-db
    image: postgis/postgis:15-3.3-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./infra/postgres/init:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  flyway-trail-svc:
    container_name: flyway-trail-svc
    image: flyway/flyway:9-alpine
    volumes:
      - ./infra/flyway/trails:/flyway/sql:ro
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://pg-db/trail-track-r
      FLYWAY_USER: flyway
      FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}
      FLYWAY_DEFAULT_SCHEMA: trails
    depends_on:
      - pg-db

  flyway-okt-import:
    container_name: flyway-okt-import
    image: flyway/flyway:9-alpine
    volumes:
      - ./infra/flyway/okt-import:/flyway/sql:ro
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://pg-db/trail-track-r
      FLYWAY_USER: flyway
      FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}
      FLYWAY_DEFAULT_SCHEMA: okt-import
    depends_on:
      - pg-db

  pg-admin:
    container_name: pgAdmin4
    image: dpage/pgadmin4:latest
    restart: on-failure
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./infra/pgadmin/servers.json:/pgadmin4/servers.json:ro
    ports:
      - 8080:80
    depends_on:
      - pg-db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@trail-track-r.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      # Application log level - one of:
      #   CRITICAL 50
      #   ERROR    40
      #   WARNING  30
      #   SQL      25
      #   INFO     20
      #   DEBUG    10
      #   NOTSET    0
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 30

volumes:
  postgres-data:
  pgadmin-data:
